export interface TraineeListNewEntryEvaluation {
    //courseDurationId: number,
    //courseNameId: number,
    // ClassLeaderName:string,
      traineeId: number,
      noitikota:number,
      sahonsheelota:number,
      utsaho:number,
      samayanubartita: number,
      manovhab:number,
      udyam:number,
      khapKhawano:number,
      onyano:number,
    // bnaAttendanceRemarksId:number,
    // attendanceStatus:boolean,
    // dateCreated:Date,
    // createdBy:string,
}