export interface ForeignCourseOtherDoc {
    foreignCourseOtherDocId: number,
    financialSanctionId:number,
    courseDurationId: number,
    courseNameId: number,
    traineeNominationId: number,
    traineeId: number,
    ticket: boolean,
    visa: boolean,
    passport: boolean,
    covidTest: boolean,
    medicalTest: boolean,
    remark:string,
    status:number,
    menuPosition: number,
    isActive: boolean,

    dgfiBreafing: boolean,
    dniBreafing: boolean,
    embassiBreafing: boolean,
    financialSanction: boolean,
    exBdLeave: boolean,
    familyGo: string,
    medicalDocument: boolean,
}
