export interface TraineeBIODataOther {
    traineeBioDataOtherId: number;
    traineeId: number;  
    bnaCurriculumTypeId: number;  
    bnaSemesterId: number;    
    utofficerTypeId: number;
    utofficerCategoryId: number;
    bnaServiceTypeId: number;
    complexionId: number; 
    branchId: number;
    heightId: number;
    weightId: number;
    colorOfEyeId: number;
    bloodGroupId: number;
    religionId: number;
    casteId: number;
    countryId: number; 
    maritalStatusId: number; 
    bnaPromotionStatusId: number; 
    bnaClassSectionSelectionId: number; 
    courseNameId: number; 
    schoolNamesId: number; 
    failureStatusId: number; 
    bnaInstructorTypeId: number; 
    presentBilletId: number; 
    age: string; 
    commissionDate: Date; 
    postCode: string; 
    identificationMark: string; 
    presentAddress: string; 
    permanentAddress: string; 
    traineeStatus: number; 
    passportNo: string; 
    drivingLiccense: string;
    bankAccount: string;
    creditCard: string;
    dateOfMarriage: Date;
    remarks: string;
    placeOfBirth: string;
    dualNationality: string;
    sNationalityId: number;
    reasonOfMigration: string;
    migrationDate: Date;
    additionalInformation: string;
    relegationDate: Date;
    relegationRemarks: string;
    relegationDocument: string;
    shortCode: string;
    isActive: boolean;
    bloodGroup:string; 
    bnaClassSectionSelection:string; 
    bnaCurriculumType:string; 
    bnaInstructorType:string;
    bnaPromotionStatus:string;
    bnaSemester:string; 
    bnaServiceType:string;
    branch:string; 
    caste: string;
    colorOfEye:string;
    complexion:string;
    courseName: string;
    country:string;
    failureStatus: string;
    height:string; 
    maritalStatus:string; 
    presentBillet:string; 
    religion:string; 
    schoolName:string;
    utofficerCategory:string; 
    utofficerType:string;
    weight: string;
} 