export interface BnaSubjectName {
    bnaSubjectNameId: number,
    bnaSemesterId: number,
    courseModuleId:  number,
    subjectCategoryId: number,
    bnaSubjectCurriculumId: number,
    courseNameId: number,
    resultStatusId: number,
    subjectTypeId: number,
    kindOfSubjectId: number,
    baseSchoolNameId: number,
    subjectClassificationId: number,
    subjectName: string,
    subjectNameBangla: string,
    subjectShortName: string,
    subjectCode: string,
    totalMark: string,
    passMarkBna:string,
    passMarkBup:string,
    classTestMark: string,
    assignmentMark: string,
    caseStudyMark:string,
    totalPeriod:string,    
    status:number,
    isActive: boolean
}