// import { Module } from './models/module'; 

// export const CUSTOMROUTES: Module[] = [
  
  
//   {
//     moduleId: 5,
//     title: 'string',
//     moduleName: 'basic-setup',
//     iconName: 'material-icons-two-tone',
//     icon: 'home',
//     class: 'menu-toggle',
//     groupTitle: false,
//     status: 0,
//     menuPosition: 0,
//     isActive: true,
//     role: ['Admin'],
//     features: [
//       {
//         featureId: 12,
//         moduleId: 5,
//         featureTypeId: 1,
//         featureName: 'check',
//         path: 'basic-setup/accounttype-list',
//         iconName: 'check',
//         icon: 'check',
//         class: 'ml-menu',
//         groupTitle: false,
//         isActive: true,
//         featureCode: 22,
//         orderNo: 3,
//         isReport: false,
//         moduleName: 'basic-setup' ,       
//       },
//       {
//         featureId: 11,
//         moduleId: 5,
//         featureTypeId: 1,
//         featureName: 'ggg',
//         path: 'basic-setup/board-list',
//         iconName: 'fff',
//         icon: 'fff',
//         class: 'ml-menu',
//         groupTitle: false,
//         isActive: true,
//         featureCode: 55,
//         orderNo: 2,
//         isReport: false,
//         moduleName: 'basic-setup',
       
//       },
//     ],
//   },
//   {
//     moduleId: 9,
//     title: 'Check',
//     moduleName: 'security',
//     iconName: 'material-icons-two-tone',
//     icon: 'home',
//     class: 'menu-toggle',
//     groupTitle: false,
//     status: 0,
//     menuPosition: 0,
//     isActive: true,
//     role: ['Admin'],
//     features: [
//       {
//         featureId: 15,
//         moduleId: 9,
//         featureTypeId: 1,
//         featureName: 'check',
//         path: 'security/user-list',
//         iconName: 'check',
//         icon: 'check',
//         class: 'ml-menu',
//         groupTitle: false,
//         isActive: true,
//         featureCode: 22,
//         orderNo: 3,
//         isReport: false,
//         moduleName: 'basic-setup' ,       
//       },
      
//     ],
//   },
// ];
