export interface BNASubjectName {
    bnaSubjectNameId: number,
    bnaSemesterId: number,
    departmentId:number,
    courseModuleId:  number,
    courseModule:string,
    subjectCategoryId: number,
    bnaSubjectCurriculumId: number,
    courseNameId: number,
    courseName: string,
    branchId:string;
    resultStatusId: number,
    subjectTypeId: number,
    kindOfSubjectId: number,
    baseSchoolNameId: number,
    subjectClassificationId: number,
    subjectName: string,
    subjectNameBangla: string,
    subjectShortName: string,
    subjectCode: string,
    totalMark: string,
    passMarkBna:string,
    // passMarkBNA:string,
    passMarkBup:string,
    classTestMark: string,
    assignmentMark: string,
    caseStudyMark:string,
    totalPeriod:string, 
    subjectGreading:number,   
    status:number,
    isActive: boolean,
    menuPosition:number,
    subjectActiveStatus:number,
    contactHour:string,
    creditHour:string
}